version: '3.8'
services:
  db:
    container_name: lovelystay_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - lovelystay_db_data:/var/lib/postgresql/data

volumes:
  lovelystay_db_data: